ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static


from django.contrib import admin
from django.urls import path
from .views import home_page, about_page, contact_page, login_page, register_page
from products.views import ProductListView, Product_list_view, ProductDetailView, Product_detail_view


urlpatterns = [
	path('',home_page),
	path('about', about_page),
	path('contact', contact_page),
	path('login', login_page),
	path('register', register_page),
    path('admin/', admin.site.urls),
    path('products', ProductListView.as_view()),
    path('products-fbv', Product_list_view),
    path('details/<pk>', ProductDetailView.as_view()),
    path('details-fbv/<pk>', Product_detail_view)

]


if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
import os
import random


def get_filename_ext(filepath):
	#print(filepath)
	
	
	name, ext = os.path.splitext(filepath)
	return name, ext


def upload_image_path(instance, filename):
	#print(instance)
	#print(filename)
	new_filename = random.randint(1,4000000000)
	name, ext = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)

	return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)


class ProductManager(models.Manager):
	def get_by_id(self,id):
		qs = self.get_queryset().filter(id=id)
		if qs.count() == 1:
			return qs.first()
		return None



class Product(models.Model):
	title        = models.CharField(max_length=120)
	description  = models.TextField()
	price        = models.DecimalField(decimal_places=2, max_digits=10, default=39.99)
	image        = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
	objects      = ProductManager()

	def __str__(self):
		return self.title

products/views.py
from django.views.generic  import ListView, DetailView 
from django.shortcuts import render, get_object_or_404
from django.http import Http404

from .models import Product


class ProductListView(ListView):
	queryset = Product.objects.all()
	template_name = 'products/list.html'

	#def get_context_data(self, *args, **kwargs):
	#	context = super(ProductListView, self).get_context_data(*args, **kwargs)
	#	print(context)
	#	return context






def Product_list_view(request):
	queryset = Product.objects.all()
	context = {
		'object_list': queryset
	}
	return render(request, 'products/list.html', context)


class ProductDetailView(DetailView):
	queryset = Product.objects.all()
	template_name = 'products/detail.html'

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
		print(context)
		#context['abc'] = 123
		return context

		def get_object(self, *args, **kwargs):
			request = self.request
			pk = self.kwargs.get('pk')
			instance = Product.objects.get_by_id(pk)
			if instance is None:
				raise Http404('product does not exist')

			return instance


def Product_detail_view(request, pk):
	#instance = Product.objects.get(pk=pk)
	#instance = get_object_or_404(Product, pk=pk)

	instance = Product.objects.get_by_id(pk)

	if instance is None:
		raise Http404('product does not exist')

	#qs = Product.objects.filter(id=pk)

	#print(qs)
	#if qs.exists() and qs.count() == 1:
	#	instance = qs.first()
	#else:
	#	raise Http404('Product does not exist')

	
	context = {
		'object': instance
	}

	return render(request, 'products/detail.html', context)

products/templates/products/detail.html
{% load static %}


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {{ object.title}}
<br>
{{ object.description }}
<br>
{% if 'object.image.exist' %}
<img src="{{ object.image.url }}" class="img-fluid">
{% endif %}


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/products/list.html
 <!-- {{qs}}




{{paginator}}
<br>
{{is_paginated}}
<br>
{{page_obj}}
<br>
{{object_list}}
<br>
{{product_list}}
<br>
{{view}}    -->




{% for obj in object_list %}

{{obj.title}}
<br>
{{obj.description }}
<br>

{% endfor %}